name: Pages
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # ratchet:actions/checkout@v3
      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # ratchet:actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
      - uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 # ratchet:gradle/gradle-build-action@v2
      - run: ./gradlew dokkaHtml
      - uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # ratchet:actions/configure-pages@v3
      - run: |
          mkdir -p _site
          mv build/dokka/html _site/api
      - uses: actions/upload-pages-artifact@66b63f4a7de003f4f00cc8e9af4b83b8f2abdb96 # ratchet:actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@ee48c7b82e077d7b8ef30b50a719e6a792a50c9a # ratchet:actions/deploy-pages@v2
        id: deployment
